# Generated by Django 3.0.7 on 2020-10-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='india_statewise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_recovered', models.IntegerField(blank=True, null=True)),
                ('active_cases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statewise_data',
            },
        ),
        migrations.CreateModel(
            name='world',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_cases', models.IntegerField(blank=True, null=True)),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_recovered', models.IntegerField(blank=True, null=True)),
                ('active_cases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'world_data',
            },
        ),
    ]
