# Generated by Django 3.0.7 on 2020-11-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_remove_world_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterModelTable(
            name='world',
            table=None,
        ),
    ]
